### ISSUE TITLE
Removing nodes from containers doesn't update sipky

### ISSUE THREAD

**Issue by fud4ly** [vanetnuggets/vanetlab-fe#12]
How to:

1. Create a container
2. Create a bunch of nodes (2+)
3. Remove a node from the container (not X on the node, but checkmark in the container's settings)

![obrázok](https://user-images.githubusercontent.com/47903327/204246997-8da2be8e-75b5-40ab-b771-6f6369a320f0.png)

If I'm not mistaken, this behaviour emerged after #10.

pls fix

**Comment by omartinka** [comment]
[branch bug-fix-polish](https://github.com/vanetnuggets/vanetlab-fe/tree/bug-fix-polish)
fix ?

**Comment by fud4ly** [comment]
hope so, let's merge
