### ISSUE TITLE
shifting canvas

### ISSUE THREAD

**Issue by samotion2** [vanetnuggets/vanetlab-fe#35]
![image](https://user-images.githubusercontent.com/56072273/225313266-b6c1ed80-605f-4ae3-9e64-60c360d442c4.png)
canvas sa posuva po otvoreni laveho draweru

**Comment by fud4ly** [comment]
Aký browser používaš?
![obrázok](https://user-images.githubusercontent.com/47903327/225320851-11a8820d-bed4-4979-94ef-950fcd3303d5.png)
Mne to v Firefoxe nerobí.

**Comment by samotion2** [comment]
skus posunut background dolava a v pravo by mal byt gap ked najprv vygenerujes nody a az potom das add network

na chrome aj mozile je to broken

**Comment by fud4ly** [comment]
stále nič, asi mi to budeš ukázať na tvojom zariadení
aký monitor máš?

**Comment by fud4ly** [comment]
![obrázok](https://user-images.githubusercontent.com/47903327/225646652-22e389d1-e657-4925-810a-9f4e80510314.png)
mne robí akurát toto, ale to je presne opak naopak xd

**Comment by fud4ly** [comment]
Tak ono to nie je problém, lebo keď movneš, tak sa to resetne 🔙

**Comment by samotion2** [comment]
user nema co resizovat window
