### ISSUE TITLE
Multiple connections are not visible

### ISSUE THREAD

**Issue by fud4ly** [vanetnuggets/vanetlab-fe#6]
When there are more than 2 connections between two nodes (see pictures below), only the last one is visible.

container1            | container2
:-------------------------:|:-------------------------:
![obrázok](https://user-images.githubusercontent.com/47903327/203644133-578d3b6f-ae3c-48a9-98e6-f81809b633a6.png) | ![obrázok](https://user-images.githubusercontent.com/47903327/203644165-6b439358-4d54-4b0c-bed2-3f84329d93ef.png)

![obrázok](https://user-images.githubusercontent.com/47903327/203644243-0a2b717a-a47f-4115-a87f-8bc111cefb85.png)

**Comment by samotion2** [comment]
known issue, will be fixed in the next sprint
